-- Fresh ecommerce source schema for CDC experiments.
-- This file creates structure only. Business data should be generated by the
-- mock API or other source-application scripts after Postgres starts.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DROP PUBLICATION IF EXISTS cdc_publication;
DROP SCHEMA IF EXISTS ecommerce CASCADE;
CREATE SCHEMA ecommerce;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cdc_user') THEN
        CREATE ROLE cdc_user WITH LOGIN PASSWORD 'cdc_password' REPLICATION;
    END IF;
END
$$;

CREATE TABLE ecommerce.customers (
    customer_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(120) NOT NULL,
    phone VARCHAR(32),
    loyalty_tier VARCHAR(20) NOT NULL DEFAULT 'BRONZE'
        CHECK (loyalty_tier IN ('BRONZE', 'SILVER', 'GOLD', 'PLATINUM')),
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive', 'suspended', 'deleted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_customers_email ON ecommerce.customers (email);
CREATE INDEX idx_customers_status ON ecommerce.customers (status);
CREATE INDEX idx_customers_loyalty_tier ON ecommerce.customers (loyalty_tier);

CREATE TABLE ecommerce.customer_addresses (
    address_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_id UUID NOT NULL REFERENCES ecommerce.customers(customer_id) ON DELETE CASCADE,
    address_type VARCHAR(20) NOT NULL DEFAULT 'shipping'
        CHECK (address_type IN ('shipping', 'billing', 'home', 'office', 'recipient')),
    recipient_name VARCHAR(120) NOT NULL,
    phone VARCHAR(32),
    line1 VARCHAR(255) NOT NULL,
    line2 VARCHAR(255),
    city VARCHAR(80) NOT NULL,
    region VARCHAR(80),
    postal_code VARCHAR(32),
    country VARCHAR(80) NOT NULL DEFAULT 'Vietnam',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_customer_addresses_customer_id ON ecommerce.customer_addresses (customer_id);
CREATE UNIQUE INDEX ux_customer_default_address_type
    ON ecommerce.customer_addresses (customer_id, address_type)
    WHERE is_default;

CREATE TABLE ecommerce.brands (
    brand_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    brand_name VARCHAR(120) NOT NULL UNIQUE,
    country VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ecommerce.categories (
    category_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    parent_category_id UUID REFERENCES ecommerce.categories(category_id) ON DELETE SET NULL,
    category_name VARCHAR(120) NOT NULL,
    category_slug VARCHAR(140) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_categories_parent_category_id ON ecommerce.categories (parent_category_id);

CREATE TABLE ecommerce.products (
    product_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    brand_id UUID REFERENCES ecommerce.brands(brand_id) ON DELETE SET NULL,
    sku VARCHAR(64) NOT NULL UNIQUE,
    product_name VARCHAR(180) NOT NULL,
    product_type VARCHAR(80) NOT NULL,
    list_price NUMERIC(12, 2) NOT NULL CHECK (list_price > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'active', 'inactive', 'discontinued')),
    specs JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_products_brand_id ON ecommerce.products (brand_id);
CREATE INDEX idx_products_product_type ON ecommerce.products (product_type);
CREATE INDEX idx_products_status ON ecommerce.products (status);

CREATE TABLE ecommerce.product_categories (
    product_id UUID NOT NULL REFERENCES ecommerce.products(product_id) ON DELETE CASCADE,
    category_id UUID NOT NULL REFERENCES ecommerce.categories(category_id) ON DELETE CASCADE,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (product_id, category_id)
);
CREATE UNIQUE INDEX ux_product_primary_category
    ON ecommerce.product_categories (product_id)
    WHERE is_primary;

CREATE TABLE ecommerce.suppliers (
    supplier_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    supplier_name VARCHAR(160) NOT NULL UNIQUE,
    contact_email VARCHAR(255),
    phone VARCHAR(32),
    country VARCHAR(80),
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive', 'suspended'))
);

CREATE TABLE ecommerce.supplier_products (
    supplier_id UUID NOT NULL REFERENCES ecommerce.suppliers(supplier_id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES ecommerce.products(product_id) ON DELETE CASCADE,
    supplier_cost NUMERIC(12, 2) NOT NULL CHECK (supplier_cost >= 0),
    lead_time_days INT NOT NULL DEFAULT 7 CHECK (lead_time_days >= 0),
    min_order_qty INT NOT NULL DEFAULT 1 CHECK (min_order_qty > 0),
    is_preferred BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (supplier_id, product_id)
);
CREATE UNIQUE INDEX ux_preferred_supplier_product
    ON ecommerce.supplier_products (product_id)
    WHERE is_preferred;

CREATE TABLE ecommerce.warehouses (
    warehouse_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    warehouse_code VARCHAR(40) NOT NULL UNIQUE,
    warehouse_name VARCHAR(160) NOT NULL,
    city VARCHAR(80) NOT NULL,
    country VARCHAR(80) NOT NULL DEFAULT 'Vietnam',
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ecommerce.inventory (
    inventory_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id UUID NOT NULL REFERENCES ecommerce.products(product_id) ON DELETE CASCADE,
    warehouse_id UUID NOT NULL REFERENCES ecommerce.warehouses(warehouse_id) ON DELETE CASCADE,
    quantity_on_hand INT NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),
    quantity_reserved INT NOT NULL DEFAULT 0 CHECK (quantity_reserved >= 0),
    reorder_level INT NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_inventory_reserved_on_hand CHECK (quantity_reserved <= quantity_on_hand),
    CONSTRAINT ux_inventory_product_warehouse UNIQUE (product_id, warehouse_id)
);
CREATE INDEX idx_inventory_product_id ON ecommerce.inventory (product_id);
CREATE INDEX idx_inventory_warehouse_id ON ecommerce.inventory (warehouse_id);

CREATE TABLE ecommerce.purchase_orders (
    purchase_order_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    supplier_id UUID NOT NULL REFERENCES ecommerce.suppliers(supplier_id),
    po_number VARCHAR(32) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'submitted', 'confirmed', 'cancelled', 'partially_received', 'received')),
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expected_at TIMESTAMPTZ,
    received_at TIMESTAMPTZ
);
CREATE INDEX idx_purchase_orders_supplier_id ON ecommerce.purchase_orders (supplier_id);
CREATE INDEX idx_purchase_orders_status ON ecommerce.purchase_orders (status);

CREATE TABLE ecommerce.purchase_order_items (
    purchase_order_item_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    purchase_order_id UUID NOT NULL REFERENCES ecommerce.purchase_orders(purchase_order_id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES ecommerce.products(product_id),
    quantity_ordered INT NOT NULL CHECK (quantity_ordered > 0),
    quantity_received INT NOT NULL DEFAULT 0 CHECK (quantity_received >= 0),
    unit_cost NUMERIC(12, 2) NOT NULL CHECK (unit_cost >= 0),
    CONSTRAINT ck_purchase_order_items_received CHECK (quantity_received <= quantity_ordered)
);
CREATE INDEX idx_purchase_order_items_po_id ON ecommerce.purchase_order_items (purchase_order_id);
CREATE INDEX idx_purchase_order_items_product_id ON ecommerce.purchase_order_items (product_id);

CREATE TABLE ecommerce.carts (
    cart_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_id UUID NOT NULL REFERENCES ecommerce.customers(customer_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'checked_out', 'abandoned', 'cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_carts_customer_id ON ecommerce.carts (customer_id);
CREATE UNIQUE INDEX ux_customer_active_cart
    ON ecommerce.carts (customer_id)
    WHERE status = 'active';

CREATE TABLE ecommerce.cart_items (
    cart_item_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    cart_id UUID NOT NULL REFERENCES ecommerce.carts(cart_id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES ecommerce.products(product_id),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price_snapshot NUMERIC(12, 2) NOT NULL CHECK (unit_price_snapshot > 0),
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_cart_items_cart_product UNIQUE (cart_id, product_id)
);
CREATE INDEX idx_cart_items_cart_id ON ecommerce.cart_items (cart_id);
CREATE INDEX idx_cart_items_product_id ON ecommerce.cart_items (product_id);

CREATE TABLE ecommerce.promotions (
    promotion_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    promo_code VARCHAR(64) NOT NULL UNIQUE,
    promotion_name VARCHAR(160) NOT NULL,
    discount_type VARCHAR(20) NOT NULL CHECK (discount_type IN ('percentage', 'fixed_amount')),
    discount_value NUMERIC(12, 2) NOT NULL CHECK (discount_value >= 0),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_promotions_date_range CHECK (ends_at > starts_at)
);

CREATE TABLE ecommerce.orders (
    order_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_id UUID NOT NULL REFERENCES ecommerce.customers(customer_id),
    shipping_address_id UUID NOT NULL REFERENCES ecommerce.customer_addresses(address_id),
    billing_address_id UUID NOT NULL REFERENCES ecommerce.customer_addresses(address_id),
    promotion_id UUID REFERENCES ecommerce.promotions(promotion_id) ON DELETE SET NULL,
    order_number VARCHAR(32) NOT NULL UNIQUE,
    order_status VARCHAR(30) NOT NULL DEFAULT 'pending_payment'
        CHECK (order_status IN (
            'pending_payment', 'payment_failed', 'paid', 'processing', 'partially_shipped',
            'shipped', 'delivered', 'cancelled', 'partially_returned', 'returned', 'refunded'
        )),
    subtotal_amount NUMERIC(12, 2) NOT NULL CHECK (subtotal_amount >= 0),
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    shipping_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (shipping_amount >= 0),
    tax_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_orders_total_amount CHECK (
        total_amount = subtotal_amount - discount_amount + shipping_amount + tax_amount
    )
);
CREATE INDEX idx_orders_customer_id ON ecommerce.orders (customer_id);
CREATE INDEX idx_orders_order_status ON ecommerce.orders (order_status);
CREATE INDEX idx_orders_ordered_at ON ecommerce.orders (ordered_at DESC);

CREATE TABLE ecommerce.order_items (
    order_item_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES ecommerce.orders(order_id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES ecommerce.products(product_id),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price > 0),
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    line_total NUMERIC(12, 2) NOT NULL CHECK (line_total >= 0),
    CONSTRAINT ck_order_items_line_total CHECK (line_total = quantity * unit_price - discount_amount)
);
CREATE INDEX idx_order_items_order_id ON ecommerce.order_items (order_id);
CREATE INDEX idx_order_items_product_id ON ecommerce.order_items (product_id);

CREATE TABLE ecommerce.payments (
    payment_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES ecommerce.orders(order_id) ON DELETE CASCADE,
    payment_method VARCHAR(30) NOT NULL
        CHECK (payment_method IN ('card', 'bank_transfer', 'cod', 'wallet', 'gift_card')),
    payment_status VARCHAR(30) NOT NULL DEFAULT 'created'
        CHECK (payment_status IN ('created', 'authorized', 'paid', 'failed', 'cancelled', 'refunded', 'partially_refunded')),
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    transaction_reference VARCHAR(120) NOT NULL UNIQUE,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_payments_order_id ON ecommerce.payments (order_id);
CREATE INDEX idx_payments_status ON ecommerce.payments (payment_status);

CREATE TABLE ecommerce.shipments (
    shipment_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES ecommerce.orders(order_id) ON DELETE CASCADE,
    carrier VARCHAR(60) NOT NULL,
    tracking_number VARCHAR(120) NOT NULL UNIQUE,
    shipment_status VARCHAR(30) NOT NULL DEFAULT 'created'
        CHECK (shipment_status IN ('created', 'packed', 'shipped', 'in_transit', 'delivered', 'failed_delivery', 'returned_to_sender')),
    shipped_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ
);
CREATE INDEX idx_shipments_order_id ON ecommerce.shipments (order_id);
CREATE INDEX idx_shipments_status ON ecommerce.shipments (shipment_status);

CREATE TABLE ecommerce.returns (
    return_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES ecommerce.orders(order_id),
    customer_id UUID NOT NULL REFERENCES ecommerce.customers(customer_id),
    return_number VARCHAR(32) NOT NULL UNIQUE,
    return_status VARCHAR(30) NOT NULL DEFAULT 'requested'
        CHECK (return_status IN ('requested', 'approved', 'rejected', 'received', 'inspected', 'refunded', 'cancelled')),
    reason TEXT NOT NULL,
    refund_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (refund_amount >= 0),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ
);
CREATE INDEX idx_returns_order_id ON ecommerce.returns (order_id);
CREATE INDEX idx_returns_customer_id ON ecommerce.returns (customer_id);
CREATE INDEX idx_returns_status ON ecommerce.returns (return_status);

CREATE TABLE ecommerce.return_items (
    return_item_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    return_id UUID NOT NULL REFERENCES ecommerce.returns(return_id) ON DELETE CASCADE,
    order_item_id UUID NOT NULL REFERENCES ecommerce.order_items(order_item_id),
    product_id UUID NOT NULL REFERENCES ecommerce.products(product_id),
    quantity_returned INT NOT NULL CHECK (quantity_returned > 0),
    refund_amount NUMERIC(12, 2) NOT NULL CHECK (refund_amount >= 0),
    item_condition VARCHAR(30) NOT NULL DEFAULT 'pending_inspection'
        CHECK (item_condition IN ('pending_inspection', 'sellable', 'damaged', 'missing_parts', 'not_received'))
);
CREATE INDEX idx_return_items_return_id ON ecommerce.return_items (return_id);
CREATE INDEX idx_return_items_order_item_id ON ecommerce.return_items (order_item_id);
CREATE INDEX idx_return_items_product_id ON ecommerce.return_items (product_id);

CREATE TABLE ecommerce.inventory_movements (
    movement_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id UUID NOT NULL REFERENCES ecommerce.products(product_id),
    warehouse_id UUID NOT NULL REFERENCES ecommerce.warehouses(warehouse_id),
    order_id UUID REFERENCES ecommerce.orders(order_id) ON DELETE SET NULL,
    purchase_order_id UUID REFERENCES ecommerce.purchase_orders(purchase_order_id) ON DELETE SET NULL,
    return_id UUID REFERENCES ecommerce.returns(return_id) ON DELETE SET NULL,
    movement_type VARCHAR(30) NOT NULL
        CHECK (movement_type IN (
            'initial_stock', 'stock_reserved', 'stock_released', 'stock_sold',
            'stock_in', 'stock_adjustment', 'transfer_out', 'transfer_in',
            'return_in', 'damaged_return', 'write_off'
        )),
    quantity_change INT NOT NULL,
    quantity_after INT NOT NULL CHECK (quantity_after >= 0),
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_inventory_movements_product_id ON ecommerce.inventory_movements (product_id);
CREATE INDEX idx_inventory_movements_warehouse_id ON ecommerce.inventory_movements (warehouse_id);
CREATE INDEX idx_inventory_movements_created_at ON ecommerce.inventory_movements (created_at DESC);

CREATE TABLE ecommerce.audit_logs (
    audit_log_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    table_name VARCHAR(80) NOT NULL,
    record_id UUID NOT NULL,
    action VARCHAR(10) NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    old_value JSONB,
    new_value JSONB,
    changed_by VARCHAR(80) NOT NULL DEFAULT CURRENT_USER,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_logs_table_name ON ecommerce.audit_logs (table_name);
CREATE INDEX idx_audit_logs_record_id ON ecommerce.audit_logs (record_id);
CREATE INDEX idx_audit_logs_changed_at ON ecommerce.audit_logs (changed_at DESC);

CREATE TABLE ecommerce.cdc_heartbeat (
    id INT PRIMARY KEY,
    ts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_cdc_heartbeat_ts ON ecommerce.cdc_heartbeat (ts DESC);

CREATE TABLE ecommerce.debezium_signals (
    id VARCHAR(64) PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    data TEXT
);

CREATE TABLE ecommerce.cdc_metrics (
    id BIGSERIAL PRIMARY KEY,
    table_name VARCHAR(80) NOT NULL,
    operation VARCHAR(10) NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
    record_count BIGINT NOT NULL DEFAULT 1,
    measured_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_cdc_metrics_table_name ON ecommerce.cdc_metrics (table_name, operation);

CREATE OR REPLACE FUNCTION ecommerce.update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION ecommerce.generate_order_number()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.order_number IS NULL OR NEW.order_number = '' THEN
        NEW.order_number := CONCAT('ORD-', EXTRACT(YEAR FROM CURRENT_DATE), '-', LPAD(NEXTVAL('ecommerce.order_number_seq')::TEXT, 6, '0'));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION ecommerce.generate_po_number()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.po_number IS NULL OR NEW.po_number = '' THEN
        NEW.po_number := CONCAT('PO-', EXTRACT(YEAR FROM CURRENT_DATE), '-', LPAD(NEXTVAL('ecommerce.po_number_seq')::TEXT, 6, '0'));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION ecommerce.generate_return_number()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.return_number IS NULL OR NEW.return_number = '' THEN
        NEW.return_number := CONCAT('RET-', EXTRACT(YEAR FROM CURRENT_DATE), '-', LPAD(NEXTVAL('ecommerce.return_number_seq')::TEXT, 6, '0'));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION ecommerce.track_table_changes()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO ecommerce.cdc_metrics (table_name, operation)
    VALUES (TG_TABLE_NAME, TG_OP);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE SEQUENCE ecommerce.order_number_seq START WITH 1;
CREATE SEQUENCE ecommerce.po_number_seq START WITH 1;
CREATE SEQUENCE ecommerce.return_number_seq START WITH 1;

CREATE TRIGGER trg_generate_order_number
    BEFORE INSERT ON ecommerce.orders
    FOR EACH ROW EXECUTE FUNCTION ecommerce.generate_order_number();

CREATE TRIGGER trg_generate_po_number
    BEFORE INSERT ON ecommerce.purchase_orders
    FOR EACH ROW EXECUTE FUNCTION ecommerce.generate_po_number();

CREATE TRIGGER trg_generate_return_number
    BEFORE INSERT ON ecommerce.returns
    FOR EACH ROW EXECUTE FUNCTION ecommerce.generate_return_number();

CREATE TRIGGER trg_update_customers_timestamp
    BEFORE UPDATE ON ecommerce.customers
    FOR EACH ROW EXECUTE FUNCTION ecommerce.update_timestamp();

CREATE TRIGGER trg_update_customer_addresses_timestamp
    BEFORE UPDATE ON ecommerce.customer_addresses
    FOR EACH ROW EXECUTE FUNCTION ecommerce.update_timestamp();

CREATE TRIGGER trg_update_products_timestamp
    BEFORE UPDATE ON ecommerce.products
    FOR EACH ROW EXECUTE FUNCTION ecommerce.update_timestamp();

CREATE TRIGGER trg_update_inventory_timestamp
    BEFORE UPDATE ON ecommerce.inventory
    FOR EACH ROW EXECUTE FUNCTION ecommerce.update_timestamp();

CREATE TRIGGER trg_update_carts_timestamp
    BEFORE UPDATE ON ecommerce.carts
    FOR EACH ROW EXECUTE FUNCTION ecommerce.update_timestamp();

CREATE TRIGGER trg_update_cart_items_timestamp
    BEFORE UPDATE ON ecommerce.cart_items
    FOR EACH ROW EXECUTE FUNCTION ecommerce.update_timestamp();

CREATE TRIGGER trg_update_orders_timestamp
    BEFORE UPDATE ON ecommerce.orders
    FOR EACH ROW EXECUTE FUNCTION ecommerce.update_timestamp();

CREATE TRIGGER trg_track_customers_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.customers
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_customer_addresses_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.customer_addresses
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_brands_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.brands
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_categories_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.categories
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_products_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.products
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_product_categories_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.product_categories
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_suppliers_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.suppliers
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_supplier_products_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.supplier_products
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_warehouses_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.warehouses
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_inventory_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.inventory
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_inventory_movements_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.inventory_movements
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_purchase_orders_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.purchase_orders
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_purchase_order_items_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.purchase_order_items
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_carts_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.carts
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_cart_items_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.cart_items
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_promotions_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.promotions
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_orders_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.orders
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_order_items_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.order_items
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_payments_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.payments
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_shipments_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.shipments
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_returns_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.returns
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();
CREATE TRIGGER trg_track_return_items_cdc AFTER INSERT OR UPDATE OR DELETE ON ecommerce.return_items
FOR EACH ROW EXECUTE FUNCTION ecommerce.track_table_changes();

CREATE PUBLICATION cdc_publication FOR TABLE
    ecommerce.customers,
    ecommerce.customer_addresses,
    ecommerce.brands,
    ecommerce.categories,
    ecommerce.products,
    ecommerce.product_categories,
    ecommerce.suppliers,
    ecommerce.supplier_products,
    ecommerce.warehouses,
    ecommerce.inventory,
    ecommerce.inventory_movements,
    ecommerce.purchase_orders,
    ecommerce.purchase_order_items,
    ecommerce.carts,
    ecommerce.cart_items,
    ecommerce.promotions,
    ecommerce.orders,
    ecommerce.order_items,
    ecommerce.payments,
    ecommerce.shipments,
    ecommerce.returns,
    ecommerce.return_items,
    ecommerce.debezium_signals;

CREATE OR REPLACE VIEW ecommerce.dashboard_metrics AS
SELECT
    (SELECT COUNT(*) FROM ecommerce.customers WHERE status = 'active') AS active_customers,
    (SELECT COUNT(*) FROM ecommerce.products WHERE status = 'active') AS available_products,
    (SELECT COUNT(*) FROM ecommerce.orders WHERE ordered_at >= CURRENT_DATE) AS orders_today,
    (SELECT COALESCE(SUM(total_amount), 0) FROM ecommerce.orders WHERE ordered_at >= CURRENT_DATE) AS revenue_today;

CREATE OR REPLACE VIEW ecommerce.cdc_replication_status AS
SELECT
    slot_name,
    active,
    restart_lsn,
    confirmed_flush_lsn,
    pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)) AS lag_size,
    EXTRACT(EPOCH FROM (NOW() - pg_last_xact_replay_timestamp())) AS lag_seconds
FROM pg_replication_slots
WHERE slot_name LIKE 'debezium%';

CREATE OR REPLACE FUNCTION ecommerce.get_table_counts()
RETURNS TABLE (
    table_name TEXT,
    row_count BIGINT,
    last_updated TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT 'customers'::TEXT, COUNT(*)::BIGINT, MAX(updated_at) FROM ecommerce.customers
    UNION ALL SELECT 'customer_addresses'::TEXT, COUNT(*)::BIGINT, MAX(updated_at) FROM ecommerce.customer_addresses
    UNION ALL SELECT 'brands'::TEXT, COUNT(*)::BIGINT, MAX(created_at) FROM ecommerce.brands
    UNION ALL SELECT 'categories'::TEXT, COUNT(*)::BIGINT, NULL::TIMESTAMPTZ FROM ecommerce.categories
    UNION ALL SELECT 'products'::TEXT, COUNT(*)::BIGINT, MAX(updated_at) FROM ecommerce.products
    UNION ALL SELECT 'product_categories'::TEXT, COUNT(*)::BIGINT, NULL::TIMESTAMPTZ FROM ecommerce.product_categories
    UNION ALL SELECT 'suppliers'::TEXT, COUNT(*)::BIGINT, NULL::TIMESTAMPTZ FROM ecommerce.suppliers
    UNION ALL SELECT 'supplier_products'::TEXT, COUNT(*)::BIGINT, NULL::TIMESTAMPTZ FROM ecommerce.supplier_products
    UNION ALL SELECT 'warehouses'::TEXT, COUNT(*)::BIGINT, NULL::TIMESTAMPTZ FROM ecommerce.warehouses
    UNION ALL SELECT 'inventory'::TEXT, COUNT(*)::BIGINT, MAX(updated_at) FROM ecommerce.inventory
    UNION ALL SELECT 'inventory_movements'::TEXT, COUNT(*)::BIGINT, MAX(created_at) FROM ecommerce.inventory_movements
    UNION ALL SELECT 'purchase_orders'::TEXT, COUNT(*)::BIGINT, MAX(ordered_at) FROM ecommerce.purchase_orders
    UNION ALL SELECT 'purchase_order_items'::TEXT, COUNT(*)::BIGINT, NULL::TIMESTAMPTZ FROM ecommerce.purchase_order_items
    UNION ALL SELECT 'carts'::TEXT, COUNT(*)::BIGINT, MAX(updated_at) FROM ecommerce.carts
    UNION ALL SELECT 'cart_items'::TEXT, COUNT(*)::BIGINT, MAX(updated_at) FROM ecommerce.cart_items
    UNION ALL SELECT 'promotions'::TEXT, COUNT(*)::BIGINT, MAX(starts_at) FROM ecommerce.promotions
    UNION ALL SELECT 'orders'::TEXT, COUNT(*)::BIGINT, MAX(updated_at) FROM ecommerce.orders
    UNION ALL SELECT 'order_items'::TEXT, COUNT(*)::BIGINT, NULL::TIMESTAMPTZ FROM ecommerce.order_items
    UNION ALL SELECT 'payments'::TEXT, COUNT(*)::BIGINT, MAX(created_at) FROM ecommerce.payments
    UNION ALL SELECT 'shipments'::TEXT, COUNT(*)::BIGINT, MAX(shipped_at) FROM ecommerce.shipments
    UNION ALL SELECT 'returns'::TEXT, COUNT(*)::BIGINT, MAX(requested_at) FROM ecommerce.returns
    UNION ALL SELECT 'return_items'::TEXT, COUNT(*)::BIGINT, NULL::TIMESTAMPTZ FROM ecommerce.return_items;
END;
$$ LANGUAGE plpgsql;

GRANT USAGE ON SCHEMA ecommerce TO cdc_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ecommerce TO cdc_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ecommerce TO cdc_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ecommerce TO cdc_user;
